### ISSUE TITLE
Add .gitignore file

### ISSUE THREAD

**Issue by kpau** [Redsart/TodoApp#1]
There are many auto-generated files that should not be part of the repository. Add `.gitignore` file to remove them.

For more information about `.gitignore` files and list of templates, see https://github.com/github/gitignore

You can use the `VisualStudio.gitignore` template for now.

**Comment by Redsart** [comment]
Done, thanks for the advice.

**Comment by kpau** [comment]
Looks good, but I will have to clone the repo and test that everything works correctly now and no required files are removed.
Will check it later today.
