### ISSUE TITLE
Enforce high code quality

### ISSUE THREAD

**Issue by kpau** [Redsart/TodoApp#19]
Enforce the use of best practices and code standards when developing the app.
Read what is static code analysis. Add it to the project.
Create a page in the [Wiki](https://github.com/Redsart/TodoApp/wiki) which will include:
- which Analizer you choose and why;
- steps to install it;
- configuration options used in the project.

Run the analysis on the project and investigate the errors. Make a list of the types of the errors and post it in this issue as a comment. We will discuss which needs fixing and which can be ignored.

See [Overview of code analysis for managed code in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/code-analysis-for-managed-code-overview?view=vs-2019) for more information.

**Comment by Redsart** [comment]
#25

**Comment by Redsart** [comment]
[https://github.com/Redsart/TodoApp.wiki.git](url)

**Comment by Redsart** [comment]
https://github.com/Redsart/TodoApp/wiki/Code-quality

**Comment by kpau** [comment]
There are still several errors coming from the code analyzer:

1. [CA1026](https://docs.microsoft.com/en-gb/visualstudio/code-quality/ca1026-default-parameters-should-not-be-used?view=vs-2015&redirectedfrom=MSDN): **Replase method 'UserInput.' with an overload that supplies all default arguments.**
The rule applies only to public methods and Microsoft does not recommend to suppress this rule. The `UserInput` class is used only in the ConsoleApp, so it should not be set as `public` at first place. Set its Access Modifier to `internal`. This should resolve the warnings.
*Reference: [Access Modifiers (C# Programming Guide)
](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers)*

2. [CA1704](https://docs.microsoft.com/en-gb/visualstudio/code-quality/ca1704-identifiers-should-be-spelled-correctly?view=vs-2015&redirectedfrom=MSDN): **Correct the spelling of 'Todo'.**
In our case this is intentionally misspelled. To resolve the warnings create `CustomDictionary.xml` file and add "Todo" as a Recognied word. See *[How to Fix Violations](https://docs.microsoft.com/en-gb/visualstudio/code-quality/ca1704-identifiers-should-be-spelled-correctly?view=vs-2015&redirectedfrom=MSDN#how-to-fix-violations)* for details.

3. [CA2210](https://docs.microsoft.com/en-gb/visualstudio/code-quality/ca2210-assemblies-should-have-valid-strong-names?view=vs-2015&redirectedfrom=MSDN): **Assemblies should have valid strong names.**
This is advanced topic, but it is recommended for an assembly to be signed with a valid strong name. To resolve this just follow the instructions under *[How to Fix Violations](https://docs.microsoft.com/en-gb/visualstudio/code-quality/ca2210-assemblies-should-have-valid-strong-names?view=vs-2015&redirectedfrom=MSDN#how-to-fix-violations) > To sign your assembly with a strong name in Visual Studio (steps 1-7)*. Follow these instructions for both projects in the solution. The "Key file name" should be the name of the project: "TodoApp.ConsoleApp" and "TodoApp.Library".

Regarding the wiki page:
- Rename the title to just "Code quality".
- Add a short install instructions (as a separate paragraph).
- How can we run the analyzer and where to see the warnings/errors?

Comments on the code will be added in the Pull Request.

**Comment by kpau** [comment]
The wiki page and the code changes looks good 👍 
There are some minor comments in the PR.
