### ISSUE TITLE
Use the Repository pattern for data persistence 

### ISSUE THREAD

**Issue by kpau** [Redsart/TodoApp#24]
The repository pattern helps encapsulating the functionality related data manipulations.

>Repositories are classes or components that encapsulate the logic required to access data sources. They centralize common data access functionality, providing better maintainability and decoupling the infrastructure or technology used to access databases from the domain model layer. If you use an Object-Relational Mapper (ORM) like Entity Framework, the code that must be implemented is simplified, thanks to LINQ and strong typing. This lets you focus on the data persistence logic rather than on data access plumbing.
>
> -- [Design the infrastructure persistence layer, Microsoft](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-design)

Useful resource: https://stackoverflow.com/questions/4819680/xml-repository-implementation

~Blocked by: #20 - Need to finish the design of the Data persistence layer.~ Repository module architecture done.

- [x] Add Repository module in ConsoleApp project.
- [x] Add Models sub-module: Add required data models.
- [x] Add Interfaces sub-module: Add IRepository and ITodoRepository.
- [x] XML sub-module: Add classes that implement IRepository and ITodoRepository.
- [x] Preferably use [LINQ to XML](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/linq-to-xml-overview)
- [x] Update Services to use the Repositories instead of classes in TodoApp.Library.
- [x] Remove the TodoApp.Library project.

Please, refer to the [architecture diagram](https://github.com/Redsart/TodoApp/tree/master/Docs) for further details.
Actual implementation might differ from the design, but the main goal must be met.

**Comment by Redsart** [comment]
#26
