### ISSUE TITLE
Refactor project to make it extendable and testable

### ISSUE THREAD

**Issue by kpau** [Redsart/TodoApp#27]
The code itself follows best practices.
The project structure and architecture can be improved to be more ease to extends.
Also some of the classes are not testable at the moment, because they do not follow the SOLID principles.

We must follow these guidelines:
- Remove all initializations from the classes (`new Something()`).
- Every class should define its dependencies as arguments in the constructor.
- Classes should depend on Interfaces / abstractions, not classes / implementations.
- All initializations should happen on single centralized place.

To do so, here is what we have to do:
- [x] Create 2 separate projects: TodoApp.Services & TodoApp.Repositories.
- [x] Move the two modules there.
- [x] Repositories / XMLRepository:
  1.  Crate folder "Utils";
  2. Move `XmlParser` in Utils; 
  3. In Utils create `interface IXmlContext` and `class XMLContext: IXmlContext`;
XmlContext will be wrapper around the actual XDocument. It will load and save the document. It will also provide a method to get the container with elements.
Single XmlContext will be used for single XML file. In single file we can keep different types of entities (e.g. Todos, Users). So the XML file should have a root element that will contain the Data containers, example:
```xml
<?xml version="1.0" encoding="utf-8"?>
<data>
  <todos>
    <todo id="..."> ... </todo>
    <todo id="..."> ... </todo>
  </todos>
  <users>
    <user id="..."> ... </user>
    <user id="..."> ... </user>
  </users>
</data>
```

  iv. RepositoryBase should receive IXmlContext, instead of path and containerName. It should use the Context in order to get and manipulate the document.

All these changes provide the following benefits:
  - Separate the repositories from the other classes inside the XML sub-module;
  - XML repositories do not load the actual file and do not depend on the file system (which makes it hard to test);
  - Single Context instance for single XML file - this will provide benefits when we add other models (e.g. User).
  - Repositories depend on interfaces so they can be tested;
  - XmlContext constructor cannot be easily unit-tested, but its single purpose is to load the XML file which is easy to test/verify without unit-test.

Diagram is updated to better illustrate:
![image](https://user-images.githubusercontent.com/1583751/80278222-34dd7d00-86fd-11ea-9d57-53257fd6e64e.png)

- [x] Services:
TodoService should depend on interface / abstraction, not on class / implementation.
It should not call `new TodoRepository()`. The repository should be provided as an argument in the constructor.
The argument and the property should be an interface (`ITodoRepository`) not a class. This way we can:
 - easily change the data source from XML to SQL;
 - mock the dependencies for unit-testing;

- [x] ConsoleApp.UI / TaskOperations:
  1. Make this class non-static!
  2. This class depends only on the TodoService. The constructor should receive ITodoService argument. Remove the `path` property.

Static is usually a bad practice. You should avoid using `static`.
If the static code manages state, it is hard to maintain - its state will be global for the whole application and can be changed from everywhere - it is hard to understand who and when can change it.  
If the static code depends on other classes, it will make it hard to test.
You can only use static for defining [pure functions](https://en.wikipedia.org/wiki/Pure_function), that you do not need to mock.

- [x] Program.cs:
This will be the place where we will initialize all the objects and manage dependencies.
After that we start the whole thing.
```cs
string path = "path/to/file.xml";
IXmlContext context = new XmlContext(path);
ITodoRepository todoRepo = new TodoRepository(context);
ITodoService todoService = new TodoService(todoRepo);
var ui = new TaskOperations(todoService);

ui.ReadOrWrite();
```

**Comment by Redsart** [comment]
#28
