### ISSUE TITLE
TodoApp.Repositories: Add unit tests

### ISSUE THREAD

**Issue by kpau** [Redsart/TodoApp#29]
Create new Unit Test Project for the Repositories.

Use **xUnit.net** for Unit test Framework and **Moq** for mocking library.
You can optionally research, investigate and compare other frameworks and libraries (e.g. NUnit, MSTest, Microsoft Fakes, JustMock).

The new project should be in new folder: "Tests".
Project name: `TodoApp.Repositories.Tests`.

Test test should be grouped. Each Repository class should have multiple Test classes, grouped in folders: e.g. tests for `TodoRepository` should be in `TodoRepository` folder.
In the folder you should have classes which test different scenarios, e.g. `class WhenContextIsEmpty` should test the behavior of `TodoRepository` when there is are no todos created.
Each class and method should have descriptive name - e.g. 'public void GetAll_ReturnsEmpty`.

Example structure of the project:
- TodoApp.ConsoleApp
- TodoApp.Repositories
- TodoApp.Services
- Tests/
  - TodoApp.Tests.Repositories
    - XmlRepository/TodoRepository/
      - WhenContextIsEmpty.cs
        - `public void GetAll_ReturnsEmpty()`

Example unit test:
```cs
using System.Xml.Linq;
using Xunit;
using Moq;
using TodoApp.Repositories.XmlRepository.Utils;
using Xml = TodoApp.Repositories.XmlRepository;

namespace TodoApp.Tests.Repositories.XmlRepository.TodoRepository
{
    public class WhenContextIsEmpty
    {
        protected Mock<IXmlContext> MockXmlContext;

        public WhenContextIsEmpty()
        {
            // Arrange
            MockXmlContext = new Mock<IXmlContext>();

            var containerName = "todos";
            var container = new XElement(containerName);

            MockXmlContext
                .Setup(ctx => ctx.GetContainer(containerName))
                .Returns(container);
        }

        [Fact]
        public void GetAll_ReturnsEmpty()
        {
            // Arrange
            var repo = new Xml.TodoRepository(MockXmlContext.Object);

            // Act
            var all = repo.GetAll();

            // Assert
            Assert.Empty(all);
        }
    }
}
```

**Comment by kpau** [comment]
If you have the same test, that asserts the same thing, but want to run it with different arguments/data, you can use `Theory` and `InlineData` attributes:
https://andrewlock.net/creating-parameterised-tests-in-xunit-with-inlinedata-classdata-and-memberdata/

```cs
[Theory]
[InlineData("20af017e-cb85-4536-8bc6-65240c5fa22c")]
[InlineData("65240c5f-cb85-4536-8bc6-20af017ea22c")]
[InlineData("cb854536-6524-0c5f-8bc6-20af017ea22c")]
public void GivenValidId_GetById_ReturnsTodoEntity(string id)
{
    // Arrange
    var repo = new Xml.TodoRepository(MockXmlContext.Object);
    var guid = new Guid(id);

    // Act
    var todo = repo.GetById(guid);

    // Assert
    Assert.NotNull(todo);
}
```
This will create 3 different tests, which will run the same code, but will use different data.

**Comment by Redsart** [comment]
#30
