### ISSUE TITLE
Console App: Refactor the main class

### ISSUE THREAD

**Issue by kpau** [Redsart/TodoApp#7]
Rename `ConsoleAppMain` class to `Program`. This class should contain only the main loop which will read and react to commands.
`Program` is a standard class name for the main entry point of the application, the same way as `Main()` is a standard method name for the entry point.

Create a new folder - `Services`. Inside, create another class `TodoService` which will be used to do the CRUD operations. This class will contain the methods for these operations.

This way we will separate the different responsibilities - one class will read and react on user commands, the other will do the actual work with the Todos.

_(CRUD = Create, Read, Update, Delete)_

**Comment by kpau** [comment]
This is set to `review` but there is no Pull-Request.
 @Redsart , please create one and link it with this issue. Thanks!

**Comment by Redsart** [comment]
#21

**Comment by Redsart** [comment]
#22 Refactor the main class #7

**Comment by kpau** [comment]
PR Merged.
